---
# Map of TEG AWS concepts
roles:
- teg-poweruser

environments:
  # Shared Dev environment
  dev:
    access: softix-dev  
    accounts:
      softix-dev:
        aws_account_id: 167856709162
        region: ap-southeast-2
    contexts:
      dev: softix-dev  
    disable_roles: true  # dev environment doesn't use assume-roles.
    
  # New TEG Sydney Environment
  sydney:
    access: teg-access
    
    accounts:
      teg-prod-au:
        aws_account_id: 167471469006
        region: ap-southeast-2
      teg-uat:
        aws_account_id: 291174894104
        region: ap-southeast-2
      teg-shared:
        aws_account_id: 159353457119
        region: ap-southeast-2
      ticketek:
        aws_account_id: 389920326251
        region: ap-southeast-2
      teg-access:
        aws_account_id: 587233433274
        region: ap-southeast-2
      teg-security:
        aws_account_id: 586874467798
        region: ap-southeast-2
    
    contexts:
      prod: teg-prod-au
      uat: teg-uat
      shared: teg-shared
      legacy: ticketek
      access: teg-access
      security: teg-security
  # New TEG Asia Environment
  asia-1:
    access: asia-1-access
    
    accounts:
      asia-1-shared:
        aws_account_id: 541441179241
        region: ap-southeast-1
      asia-1-ticketek-prod:
        aws_account_id: 157925055900
        region: ap-southeast-1
      asia-1-ticketek-uat:
        aws_account_id: 680087473670
        region: ap-southeast-1
      asia-1-access:
        aws_account_id: 622668753165
        region: ap-southeast-1
      asia-1-security:
        aws_account_id: 603539520371
        region: ap-southeast-1
    
    contexts:
      prod: asia-1-ticketek-prod
      uat: asia-1-ticketek-uat
      shared: asia-1-shared
      legacy: null
      access: teg-technology-asia-1-access
      security: asia-1-security
